#!/bin/bash

COMPOSITION=$1
SKELETON="allIsomers-10.txt"

RUN="./lumpacview.exe generateCompositionFiles 6 30 12 3 $COMPOSITION $SKELETON pc"

$RUN

for i in `seq 2 3`;
do
cd Block$i
./runBlock.x
cd ..
done

./lumpacview.exe cleanBlocks $COMPOSITION 6 3 pc

MID="independent-isomers-"
LAST=$COMPOSITION"-independent-isomers-"

cat $COMPOSITION---atomTypes.txt  $LAST* > results-$COMPOSITION 
rm $COMPOSITION---atomTypes.txt
rm $LAST*
rm $MID*

wc -l -w "results-"$COMPOSITION 


