#!/bin/bash

# quando o weights nao e gerado da falha na segmentacao

COMPOSITION=$1

SYSTEM="6"
NPERMUTATIONS="30"
BIGBLOCK="8"
SMALLBLOCK="8"
SKELETON="isomers-6"
NBLOCKS="4"
WAIT="36"

./lumpacview.exe generateCompositionFiles $SYSTEM $NPERMUTATIONS $BIGBLOCK $SMALLBLOCK $COMPOSITION $SKELETON slurm

for i in `seq 2 $NBLOCKS`;
do
cd Block$i
./runBlock.x
cd ..
done

./lumpacview.exe waitSlurm $WAIT

./lumpacview.exe cleanBlocks $COMPOSITION $SYSTEM $NBLOCKS slurm

./lumpacview.exe waitSlurm $WAIT

./lumpacview.exe buildCsvFile $SYSTEM $SKELETON

mv allIsomers-final.csv final-$COMPOSITION

cat final-$COMPOSITION | sed '/^\s*$/d' | wc -l > count-$COMPOSITION

rm *.csv
rm slurm*
rm independent*
rm *.srm
rm runBlock*
rm $COMPOSITION*
rm *.txt


# tenho que escolher numeros pares para apagar que ele nao vai separar
# os caras.
# outro cuidado e o esqueleto comecar com 0 1 2 3 4 5...
# e no esqueleto a ultima linha tem q ser apagada
