#!/bin/bash

COMPOSITION0=$1

COMPOSITION=$COMPOSITION0" "

if [ "$COMPOSITION" == " " ]
then
	exit
fi


SYSTEM="8"
NPERMUTATIONS="5040"
BIGBLOCK="100"
SMALLBLOCK="100"
SKELETON="enantiomers-8"
NBLOCKS="51"
WAIT="2"

./lumpacview.exe generateCompositionFiles $SYSTEM $NPERMUTATIONS $BIGBLOCK $SMALLBLOCK $COMPOSITION $SKELETON slurm

for i in `seq 2 $NBLOCKS`;
do
cd Block$i
./runBlock.x
cd ..
done

./lumpacview.exe waitSlurm $WAIT

./lumpacview.exe cleanBlocks $COMPOSITION $SYSTEM $NBLOCKS slurm

./lumpacview.exe waitSlurm $WAIT

./lumpacview.exe buildCsvFile $SYSTEM $SKELETON

mv allIsomers-final.csv final-$COMPOSITION

rm *.csv
rm slurm*
rm independent*
rm *.srm
rm runBlock*
rm $COMPOSITION*
rm *.txt


# tenho que escolher numeros pares para apagar que ele nao vai separar
# os caras.
# outro cuidado e o esqueleto comecar com 0 1 2 3 4 5...
# e no esqueleto a ultima linha tem q ser apagada
